kind: Pod
apiVersion: v1
metadata:
  name: smb-client
spec:
  containers:
    - name: smb-client
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /smbshare
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: smb-pvc
