apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-simple-csi
provisioner: seitenbau.csi.smb
parameters:
  source: "//10.96.0.149/share"
  server: "10.96.0.149"
  share: "share"
  csi.storage.k8s.io/node-stage-secret-name: "my-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=1001
  - gid=1001
