kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-cloned
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb-csi
  dataSource:
    name: pvc-smb
    kind: PersistentVolumeClaim
