kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-snap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb-csi
  dataSource:
    name: smb-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
