apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-static
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: seitenbau.csi.smb
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//10.96.0.149/share"
    nodeStageSecretRef:
      name: my-secret
      namespace: default
