apiVersion: v1
kind: Service
metadata:
  name: controllerserver
spec:
  ports:
    - port: 80
  selector:
    app: controllerserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controllerserver
  namespace: kube-system
spec:
  serviceName: controllerserver
  selector:
    matchLabels:
      app: controllerserver
  template:
    metadata:
      labels:
        app: controllerserver
    spec:
      serviceAccountName: controller-account
      containers:
        - name: driver
          image: seitenbau/smb-csi-driver
          imagePullPolicy: IfNotPresent
          args:
            - --nodeid=$(NODEID)
          env:
            - name: NODEID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: driversocket
              mountPath: /csi

        - name: external-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
          args:
            - -v=2
            - --csi-address=/csi/csi.sock
            - --leader-election
          volumeMounts:
            - mountPath: /csi
              name: driversocket

        - name: external-attacher
          image: gcr.io/k8s-staging-sig-storage/csi-attacher:canary
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --leader-election
          volumeMounts:
            - mountPath: /csi
              name: driversocket

        - name: external-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --leader-election=false
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /csi
              name: driversocket

      volumes:
        - name: driversocket
          emptyDir: {}
