apiVersion: apps/v1
kind: Deployment
metadata:
  name: glusterfs-simple-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glusterfs-simple-provisioner
    spec:
      serviceAccountName: glfs-provisioner
      containers:
        - name: glusterfs-simple-provisioner
          image: "quay.io/external_storage/glusterfs-simple-provisioner:latest"
  selector:
    matchLabels:
      app: glusterfs-simple-provisioner
